version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/api" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/graph-updater" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/event-collectors/github-webhook-server/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/ui" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/scanners/github-cloned-repo" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/scanners/github-octokit" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/scanners/web-endpoint"  # Correct indentation here
    schedule:
      interval: "weekly"
