productName: Observatory
webEndpoints:
  - https://safeinputs.phac.alpha.canada.ca
  - https://hopic-sdpac.phac-aspc.alpha.canada.ca
  - https://hopic-sdpac.k8s.phac-aspc.alpha.canada.ca
  - https://safeinputs.phac.alpha.canada.ca/graphql
  - https://api.example.com/api/fakeEndpoint
  - https://graphql-api.phac.canada.ca
  - https://graphql-ipa.aspc.canada.ca
domains:
  - entreessecurisees.aspc.alpha.canada.ca
  - safeinputs.phac-aspc.alpha.canada.ca
  - safeinputs.phac.alpha.canada.ca
containerEndpoints:
  - northamerica-northeast1-docker.pkg.dev/phx-01h1yptgmche7jcy01wzzpw2rf/hello-world-app
