apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Deploy the repositories
- repositories.yaml

# Kubernetes service account for external secrets
- service-account.yaml

- external-secrets.yaml

patches:
- target:
    group: ""
    version: v1
    kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
  patch: |-
    - op: add
      path: /metadata/annotations
      value:
        iam.gke.io/gcp-service-account: external-secrets@phx-01h8eq9sbx7d19zsvqk7t9zymr.iam.gserviceaccount.com