---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ruok-ui-image-repo
  namespace: flux-system
spec:
  image: vader404/ruok-ui
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ruok-ui-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ruok-ui-image-repo
  policy:
    semver:
      range: '>=0.0.1'
# ---
# apiVersion: image.toolkit.fluxcd.io/v1beta1
# kind: ImageUpdateAutomation
# metadata:
#   name: ruok-ui-image-deployment-updater
#   namespace: flux-system
# spec:
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   interval: 5m
#   update:
#     strategy: Setters
#     path: ./k8s/ui-revived
#   git:
#     checkout:
#       ref:
#         branch: ui-revived
#     commit:
#       author:
#         name: fluxbot
#         email: fluxcd@users.noreply.github.com
#       messageTemplate: "[ci skip] {{range .Updated.Images}}{{println .}}{{end}}"
#     push:
#       branch: ui-revived