apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./arangodeployment-single-server.yaml
- ./deployment-nats.yaml
- ./deployment-ui-server.yaml
- ./deployment-ruok-api.yaml
- ./deployment-webhook-server.yaml
- ./deployment-graph-updater.yaml
- ./deployment-octokit-scanner.yaml
- ./deployment-web-endpoint-scanner.yaml
- ./deployment-cloned-repo-scanner.yaml
- ./svc-nats.yaml
- ./svc-ruok-api.yaml
- ./svc-webhook-server.yaml
patches:
- target:
    version: v1
    kind: Deployment
    name: graphql-api
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: DB_HOST
          value: http://example-simple-single-ea:8529
- target:
    version: v1
    kind: Deployment
    name: webhook-server
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: NATS_SERVER
          value: nats:4222
        - name: NATS_PUB_STREAM
          value: EventsUpdate
- target:
    version: v1
    kind: Deployment
    name: graph-updater
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: NATS_URL
          value: nats:4222
        - name: GRAPHQL_URL
          value: http://graphql-api:4000/graphql
- target:
    version: v1
    kind: Deployment
    name: cloned-repo-scanner
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: NATS_URL
          value: nats:4222
        - name: GRAPHQL_URL
          value: http://graphql-api:4000/graphql
- target:
    version: v1
    kind: Deployment
    name: octokit-scanner
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: NATS_URL
          value: nats:4222
        - name: GRAPHQL_URL
          value: http://graphql-api:4000/graphql
- target:
    version: v1
    kind: Deployment
    name: web-endpoint-scanner
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: NATS_URL
          value: nats:4222
        - name: GRAPHQL_URL
          value: http://graphql-api:4000/graphql
