---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: image-automation-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: ./k8s/image-automation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system