---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ui-revived
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/ui-revived
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
