apiVersion: v1
kind: Service
metadata:
  name: ruok-ui
  namespace: default
spec:
  selector:
    app: ruok-ui
  ports:
    # - port: 4000
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: 30036
