apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert-letsencrypt-dns
  namespace: istio-system
spec:
  secretName: tlskeys-letsencrypt-dns
  issuerRef:
    # The issuer created previously
    name: letsencrypt-dns
  dnsNames:
  - observatory.alpha.phac.gc.ca