apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-dns
  namespace: istio-system
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: siddhartha.haldar@phac-aspcgc.ca
    privateKeySecretRef:
      name: letsencrypt-dns
    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: phx-01h7dnj5j46f52sev8akqd9m7g
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: clouddns
            key: clouddns.key.json