# Letsencrypt Production
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  # name: letsencrypt
  name: self-signed
  # (Optional) Metadata
  # namespace: your-namespace
  namespace: istio-system
spec:
  selfSigned: {}
  # acme:
  #   solvers: []
  #   preferredChain: ""
  #   # Letsencrypt Production
  #   privateKeySecretRef:
  #     name: letsencrypt-prod
  #   server: https://acme-v02.api.letsencrypt.org/directory
